Fixes #418: compilation error due to isspace() in usddeck.c
HINT: On Ubuntu 16.04 it resolves the error: array subscript has type
'char' [-Werror=char-subscripts] as all warnings are treated as errors.